[package]
name = "strongly-connected-components"
version = "0.1.0"
edition = "2024"
authors = ["Marek Sommer <rust_scc.refinish266@passmail.net>"]
repository = "https://github.com/mareksom/strongly-connected-components"
documentation = "https://docs.rs/strongly-connected-components"
description = "Decomposes a graph into Strongly Connected Components and to sorts them in topological order."
license = "MIT"
keywords = ["strongly-connected-components", "scc", "tarjan", "topological-order", "graph"]
categories = ["algorithms"]

[dev-dependencies]
rand = "0.9"
rand_chacha = "0.9"
rstest = "0.26"
